#! /bin/sh
#JAVA_HOME=/usr/java/jre1.6.0
MEDIACHEST_HOME=$HOME/MediaChest
# $Id: MediaChest,v 1.11 2012/12/02 21:44:46 cvs Exp $
java -jar $MEDIACHEST_HOME/lib/MediaChest.jar -Djdbc.drivers=sun.jdbc.odbc.JdbcOdbcDriver -DMediaChest.home=$MEDIACHEST_HOME/data -DR-AddressBook.home=$MEDIACHEST_HOME/data photoorganizer.PhotoOrganizer
